x=input("Name")
y=input("Age")
z=input("College name")
x=(str(x))
y=(int(y))
z=(str(z))
print("my name is %s my age is %s my college name is %s" %(x,y,z))
print("Marks obtained:")
SM=input("marks of simulation and modeling:")
AI=input("marks of artificial intelligence:")
CR=input("marks of cryptograpy:")
CN=input("marks of computer network:")
DAA=input("marks of design of data algorithm and analysis:")
SM=int(SM)
AI=int(AI)
CR=int(CR)
CN=int(CN)
DAA=int(DAA)
sum=SM+AI+CR+CN+DAA
print("Total marks is: %s " %(sum))

